apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
    name: iam-role-access-advisor
    description: |
        AWS IAM Least Privilege Automation
    tags:
        - ubreakifix
        - documentation
        - typescript
        - iam
    annotations:
        github.com/project-slug: asurion-private/iam-role-access-advisor
        backstage.io/techdocs-ref: url:https://github.com/asurion-private/iam-role-access-advisor/tree/main
    namespace: default
spec:
    type: Service
    owner: pse-admins
    lifecycle: production
    system: shared-catalog
