# AFRAME Config File

cicd:
  workflowProps:
    preWorkflowPropsCommand: 
    deployIamRole: ${{ inputs.role }}
    nvmFilePath:
    nodeCacheType: npm
    nodeCacheDependencyPath: ./package-lock.json
    postWorkflowPropsCommand: 
    jobSummary: 🚀
  workflowCommands:
    preWorkflowCommandsCommand: 
    dependencyInstallCommand: npm i
    buildCommand: npm install -g typescript
    deployCommand: npm run poc 
    postWorkflowCommandsCommand: 
  environmentVariables:
    ENV: feat
  rfc:
    preRFCCommand: 
    templateID: 
    description: 
    changePlan: 
    postRFCCommand: 
  deployment:
    preDeploymentCommand: 
    targetURL: 
    environment: 
    postDeploymentCommand: 
  slack:
    preSlackCommand: 
    channel: 
    payLoadFilePath: 
    postSlackCommand: 
  uploadArtifact:
    name:
    path:
  callWorkflow:
    preCallWorkflowCommand: 
    repoName: 
    branchName: 
    workflowName: 
    inputsFilePath: 
    postCallWorkflowCommand: 
