name: Aframe Shared Workflow

on:
  workflow_dispatch:

jobs:
  call-workflow-passing-data:
    uses: asurion-private/afr-shared-workflow/.github/workflows/shared-workflow.yaml@feat/upload-artifact-implementation
    with:
      repo: iam-role-access-advisor
      branchToCheckout: main
      runner: common-8gb-or-smaller
      aframeFilePath: ./infra/aframe.prod.yaml
