name: Tech Docs Publish

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'docs/**.md'
      - 'mkdocs.yml'
      - 'README.md'
      - 'catalog-info.yaml'

jobs:
  build:
    uses: asurion-private/pse-github-actions/.github/workflows/backstageDocPush.yaml@main
    with: 
      rootReadMe: true