name: Generate Inline Policies for Roles

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Choose an environment
        options:
        - UBIF-NONPROD

jobs:
  generate:
    runs-on: [self-hosted, common-8gb]
    env:
      GITHUB_TOKEN: ${{ secrets.ORG_GITHUB_TOKEN }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
         node-version: 18

    - name: NPM Install
      run: npm install

    - name: Set Environment
      run: export AWS_PROFILE=ubreakifix-nonprod.appadmins

    - name: Generate
      run: npm run generate

    - name: Archive Results 
      uses: actions/upload-artifact@v3
      with:
        name: results
        path: results/