name: Prepare SRE-Stage Pull Request for CI/CD Release Deployment
on:
  workflow_dispatch:
  push:
    branches:
      - sre-stage
    
jobs:
  scheduled-pull-request:
    runs-on: common-8gb
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Create Pull Request
      uses: actions/github-script@v6
      with:
        script: |
          const { repo, owner } = context.repo;

          const comparison = await github.rest.repos.compareCommits({
            owner: owner,
            repo: repo,
            base: 'main',
            head: 'sre-stage'
          });

          const commitMessages = comparison.data.commits.map(commit => commit.commit.message).join(" ");
          const extractedTicketCommits = [...new Set(commitMessages.match(/DS-[0-9]+/g))];
          const ticketSummary  = extractedTicketCommits.length == 0 ? '[No commits with ticket numbers yet]' : extractedTicketCommits.join(" ");

          console.log('Commit Messages: ', commitMessages);
          console.log('Ticket Summary: ', ticketSummary);

          const currentDate = new Date().toISOString().split('T')[0];

          const pullRequestTitle = `${ticketSummary} : SRE-Stage to Master : [insert RFC ticket] CI/CD Release ${currentDate}`

          const pulls = await github.rest.pulls.list({
              owner: owner,
              repo: repo,
              head: 'sre-stage',
              base: 'main',
              state: 'open',
          });

          const sreStagePull = pulls.data.find(pr => pr.head.ref === 'sre-stage');

          if (sreStagePull === null || sreStagePull === undefined) {
            await github.rest.pulls.create({
              title: pullRequestTitle,
              owner: owner,
              repo: repo,
              head: 'sre-stage',
              base: 'main'
            });
          } 
          
          else {
            await github.rest.pulls.update({
              title: pullRequestTitle,
              owner: owner,
              repo: repo,
              pull_number: sreStagePull.number
            });
          }